### ISSUE TITLE
Textnets not available for R version 3.6.1

### ISSUE THREAD

**Issue by rkapitany** [cbail/textnets#10]
Hi Chris,

You're textnets tutorial was very clear and, fortunately, exactly what I needed to explore my own dataset. However, I'm encountering a problem. When I try to install textnets, I get the follow message:

package ‘cbail/textnets’ is not available (for R version 3.6.1)

This has been true one one computer running different versions of R (inc. 3.4), and also true on two other computers that were all version 3.6. I've downloaded textnets and tried to install it from a local directory rather than a grab. 

I'm afraid I'm not particularly savvy in this regard, but is there a version textnets is available for? Has something happened at the github end? 

Thanks in advance,
- rohan

**Comment by cbail** [comment]
Hi Rohan:

The package is not on CRAN, so you have to install it you using the install_github() command within the devtools package (this is described in our documentation). All the best!

**Comment by rkapitany** [comment]
Thank you very much for your prompt response. Somehow I simply wasn't following your instructions correctly, my bad!

Great package, very useful!

**Comment by fmerhout** [comment]
Hi Rohan, just chiming in here quickly. As Chris mentioned, unfortunately, textnets is not on CRAN yet and compatibility with different versions of R is limited. However, I just tried installing from github on my machine and did not encounter any issues. I am running R version 3.5.3 If you can can install that version of R on your machine, this code should allow you to install textnets:

    install.packages("devtools")
    library("devtools")
    install_github("cbail/textnets")
