### ISSUE TITLE
Error in lazy loading

### ISSUE THREAD

**Issue by spono** [cbail/textnets#12]
Hi,
your package looks superinteresting but I get the following error while installing the package:

```
Installing package into ‘D:/Documenti/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'textnets' ...
** using staged installation
** R
** data
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'dplyr' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'textnets'
* removing 'D:/Documenti/R/win-library/3.6/textnets'
Error: Failed to install 'textnets' from GitHub:
  (converted from warning) installation of package ‘C:/Users/sciur/AppData/Local/Temp/RtmpwxGSOm/file33c842677ac4/textnets_0.1.1.tar.gz’ had non-zero exit status
```

How could it be solved?

Thanks in advance!

**Comment by yl17124** [comment]
HI @spono 
First, I suggest to try put `dependencies=TRUE` after cbail's repo's path like this: 
install_github("cbail/textnets", dependencies=TRUE).

or, replace `dependencies=TRUE` with `R_REMOTES_NO_ERRORS_FROM_WARNINGS= TRUE ` to avoids stopping the installation for warning messages. 
please, refer this [document](https://github.com/r-lib/remotes#environment-variables).

**Comment by spono** [comment]
hi, thank you very much!
unfortunately none of the solutions worked.
I'll try updating to the latest R version, even though looks strange this appears to be a blocker issue

**Comment by lucas-dopaes** [comment]
I have had exactly the same issue and I'm not being able to install the package. The package seems super helpful and I would love to explore it. Does anyone know how to solve this installation issue?
Thanks

**Comment by cbail** [comment]
Hi- hard to help without knowing more about what type of system you are on, what version of R, etc. Unfortunately I don't have much time to maintain this package these days, so if you are really stuck it might be easiest to just cut and paste the functions into your R session and adapt accordingly?

**Comment by spono** [comment]
@lucas-dopaes I erased R&packages, updated to the latest and worked fine...I don't know to what it was related but probably to some kind of broken API

**Comment by lucas-dopaes** [comment]
Hi - many thanks you both. I couldn't manage to solve it, but following cbail suggestion, I managed to use the copy-paste the code and adapt. Many thanks!
