### ISSUE TITLE
PrepTextSent function not found

### ISSUE THREAD

**Issue by yueliosu** [cbail/textnets#17]
I was trying to use the PrepTextSent function, but the error message says:

Error in PrepTextSent(whb_tn, groupvar = "speaker", textvar = "textvar",  : 
  could not find function "PrepTextSent"

Is the function still being developed so that we cannot use it currently?

Thank you for your help!

**Comment by cbail** [comment]
Hi- it's currently a hidden function (in the development folder), so you'd have to copy and paste the function into your environment and run/define it before using it. Let me know if you get some interesting results- it is not yet working as well as I would like :(
