### ISSUE TITLE
Cells of the adjacency matrix

### ISSUE THREAD

**Issue by yueliosu** [cbail/textnets#27]
Dear Professor Bail, 

I hope you are doing well! I'm currently trying to do some further analyses using the adjancy matrix created by Textnets. So, I would like to know how the values of the cells are calculated conceptually. It says in the demo that "the cells of the adjacency matrix are the transposed crossproduce of the term-frequency inverse-document frequency (TFIDF) for overlapping terms between two documents for PrepText." Could you please elaborate on this a bit more conceptually and mathematically?

Thank you for your help in advance!
Yue

**Comment by cbail** [comment]
Please see: http://www.pnas.org/content/113/42/11823.full.pdf?with-ds=yes

**Comment by yueliosu** [comment]
> Please see: http://www.pnas.org/content/113/42/11823.full.pdf?with-ds=yes

Thanks for your quick reply! I found it at the end of the paper! 
Yue
