### ISSUE TITLE
Install on R 3.5 Ubuntu 18

### ISSUE THREAD

**Issue by thousandoaks** [cbail/textnets#8]
Hi, I am getting an installation issue (R 3.5. Ubuntu 18)
library(devtools)
> install_github("cbail/textnets")
Downloading GitHub repo cbail/textnets@master
from URL https://api.github.com/repos/cbail/textnets/zipball/master
Installation failed: error in running command

Thanks

**Comment by cbail** [comment]
Have you tried this?:

https://www.digitalocean.com/community/tutorials/how-to-install-r-packages-using-devtools-on-ubuntu-16-04
