### ISSUE TITLE
Error with CreateTextNet function

### ISSUE THREAD

**Issue by CG-Rodriguez** [cbail/textnets#9]
Whenever I try to use the CreateTextNet function, I get an error message:

``` 
> data("sotu")
> sotu_first_speeches <- sotu %>% group_by(president) %>% slice(1L)
> sotu_firsts_network <- CreateTextnet(sotu_first_speeches)
Error in tapply(n, documents, sum) : arguments must have same length
```
Any ideas? Thanks!

**Comment by fmerhout** [comment]
Hi @CG-Rodriguez,

Thank you for using our package! `CreateTextNet` takes a tidytext dataframe as an input, such as created by `PrepText`. You need to turn your text data into the appropriate format before passing it to `CreateTextNet`.

Hope this helps.

**Comment by CG-Rodriguez** [comment]
Hi @fmerhout 

That's exactly what I'm doing; I'm using `PrepText` with the dataset provided by the package.  I still can't figure out what's going on here.

**Comment by fmerhout** [comment]
Can you send the exact code you are using? The snippet you originally included is missing the preparation step.

Thank you.
